### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [tobyjamesthomas/pi#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a LICENSE - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

**Comment by tobyjamesthomas** [comment]
Thanks Joe! I appreciate it!

**Comment by unixorn** [comment]
Added in https://github.com/unixorn/awesome-zsh-plugins/pull/665
